services:
  mousequetaire-site:
    build: .
    container_name: mousequetaire-site
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - mousequetaire-site
